services:
  # Бэкенд сервер
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: interview-backend
    ports:
      - "5001:5000"
    volumes:
      - ./server/database.sqlite:/app/database.sqlite
      - ./server/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - interview-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Фронтенд сервер
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: interview-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - interview-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  interview-network:
    driver: bridge

volumes:
  database:
    driver: local
  uploads:
    driver: local
